{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nxcc.fullname" . }}
  labels:
    {{- include "nxcc.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- /* If paths are not specified for a host, provide a default to prevent an invalid Ingress resource. */}}
          {{- $paths := .paths | default (list (dict "path" "/" "pathType" "ImplementationSpecific")) -}}
          {{- range $paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "nxcc.fullname" $ }}-worker
                port:
                  name: http
          {{- end }}
          {{- if gt (int $.Values.seed.replicaCount) 0 }}
          - path: /seed
            pathType: Prefix
            backend:
              service:
                name: {{ include "nxcc.fullname" $ }}-seed-http
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
