syntax = "proto3";
package secrets;

message SecretIdentifier {
  uint64 chain_id = 1;
  string identity_address = 2;
  string identity_id = 3;
}

message GetSecretsBatchRequest {
  repeated SecretIdentifier secrets = 1;
  bytes payload = 2;
}

message EncryptedSecret {
  bytes data = 1;
  string metadata = 2;
  uint64 chain_id = 3;
  string identity_address = 4;
  string identity_id = 5;
}

message GetSecretsBatchResponse {
  repeated EncryptedSecret secrets = 1;
}

service Secrets {
  rpc GetSecretsBatch(GetSecretsBatchRequest) returns (GetSecretsBatchResponse);
}
