use std::collections::HashMap;

use once_cell::sync::Lazy;

pub mod types;
use types::Chain;

/// A map of chain IDs to chain data, loaded from the generated JSON file.
///
/// The JSON file is generated by the `nxcc-chainlist-gen` binary.
pub static CHAINS: Lazy<HashMap<u64, Chain>> = Lazy::new(|| {
    let json_str = include_str!("chains.json");
    let chains: Vec<Chain> = serde_json::from_str(json_str)
        .expect("Failed to parse chains.json; run `nxcc-chainlist-gen` binary to generate it.");
    chains.into_iter().map(|c| (c.chain_id, c)).collect()
});

/// Retrieves chain data for a given chain ID.
///
/// # Example
///
/// ```
/// use nxcc_chainlist::get_chain;
///
/// // Get data for Ethereum Mainnet
/// if let Some(chain) = get_chain(1) {
///     println!("Chain Name: {}", chain.name);
///     if let Some(rpc_url) = chain.rpcs.https.first() {
///         println!("First HTTPS RPC: {}", rpc_url);
///     }
/// }
/// ```
pub fn get_chain(chain_id: u64) -> Option<&'static Chain> {
    CHAINS.get(&chain_id)
}
