syntax = "proto3";

package daemon;

import "interface.proto";

// Daemon notification service
service Daemon {
  rpc BroadcastNotification (BroadcastRequest) returns (BroadcastResponse);
}

message BroadcastRequest {
  string message = 1;
}

message BroadcastResponse {
  bool success = 1;
}

// Secrets service
service Secrets {
  rpc GetSecrets (GetSecretsRequest) returns (GetSecretsResponse);
  rpc AttachVm (AttachVmRequest) returns (AttachVmResponse);
}

message GetSecretsRequest {
  repeated interface.SecretRequest secret_requests = 1;
  interface.EnvReport env_report = 2;
}

message GetSecretsResponse {
  interface.SecretsBox secrets_box = 1;
}

message AttachVmRequest {
  string vm_id = 1;
  string uds_path = 2;
}

message AttachVmResponse {
  bool success = 1;
}
