[package]
name = "nxcc-interface"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { version = "1.5.2", features = ["serde"] }
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
ciborium = "0.2.2"
prost = "0.14.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
url = { version = "2.5.8", features = ["serde"] } # Added for WorkerManifest
thiserror = "2.0.18"
tonic = { version = "0.14.2", features = ["transport"] }
tonic-prost = "0.14.2"
alloy-rpc-types = "1.5.2"
anyhow = "1.0"
async-trait = "0.1"
ed25519-dalek = "2.2.0"

[build-dependencies]
tonic-prost-build = "0.14.2"
