[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
nxcc-interface = { path = "../node/interface" }
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.14.2", features = ["transport", "codegen"] }
prost = "0.14.3"
clap = { version = "4", features = ["derive"] }
hdrhistogram = "7.5"
indicatif = "0.18.3"
serde_json = "1.0"
base64 = "0.22.1"
anyhow = "1.0"
futures = "0.3"
alloy-primitives = "1.5.2"
reqwest = { version = "0.13", features = ["json"] }
alloy-sol-types = { version = "1.5.2", features = ["json"] }
alloy-provider = { version = "1.5.2", features = ["ws", "pubsub", "reqwest", "reqwest-default-tls"] }
alloy-rpc-types = "1.5.2"
alloy-contract = "1.5.2"
url = "2.5"
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.9.3"
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
alloy-signer-local = "1.5.2"

[profile.release]
codegen-units = 1
lto = "thin"
