use std::{
    collections::{BTreeMap, HashMap, HashSet},
    sync::Arc,
};

use ethers::types::{Address, H256};
use futures::channel::mpsc;
use serde::{Deserialize, Serialize};
use tokio::sync::{Mutex, RwLock, oneshot};
use tracing::{debug, error, warn};

use crate::{error::AppError, network::SecretsMessage};

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq, Serialize, Deserialize, PartialOrd, Ord)]
pub struct SecretId {
    pub chain_id: u64,
    pub identity_address: Address,
    pub identity_id: H256,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretRequest {
    /// Hash of the worker that will use the secret
    pub consumer: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretRequesterInfo {
    /// The attestation generated by the requester secrets enclave
    pub report: Vec<u8>,
    /// The public key of the requesting secrets enclave (for key encapsulation)
    pub public_key: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretsBox {
    /// Include cipher/kem and signature alg
    pub alg: String,
    pub nonce: Vec<u8>,
    pub sender_public_key: Vec<u8>,
    pub payload: Vec<u8>,
    pub signature: Vec<u8>,
}

#[derive(Debug, Clone)]
#[cfg_attr(debug_assertions, derive(Serialize, Deserialize))]
pub struct Secret {
    pub id: SecretId,
    pub data: Vec<u8>,
    pub metadata: Vec<u8>,
}

pub struct SecretsService {
    p2p_secrets_sender: mpsc::Sender<SecretsMessage>,
    store: RwLock<HashMap<SecretId, Secret>>,
    pending: Mutex<HashMap<u64, PendingRequest>>,
    request_counter: Mutex<u64>,
}

struct PendingRequest {
    requested_ids: HashMap<SecretId, Vec<SecretRequest>>,
    requester_info: SecretRequesterInfo,
    threshold: usize,
    collected: HashMap<SecretId, Secret>,
    responder:
        oneshot::Sender<Result<(HashMap<SecretId, Vec<SecretRequest>>, SecretsBox), AppError>>,
}

impl SecretsService {
    pub fn new(p2p_secrets_sender: mpsc::Sender<SecretsMessage>) -> Arc<Self> {
        Arc::new(Self {
            p2p_secrets_sender,
            store: RwLock::new(HashMap::new()),
            pending: Mutex::new(HashMap::new()),
            request_counter: Mutex::new(0),
        })
    }

    pub async fn probe_secrets(
        &self,
        secret_ids: impl IntoIterator<Item = SecretId>,
    ) -> Result<HashSet<SecretId>, AppError> {
        let snapshot = self.store.read().await;
        let found = secret_ids
            .into_iter()
            .filter(|id| snapshot.contains_key(id))
            .collect();

        Ok(found)
    }

    pub async fn get_secrets(
        self: &Arc<Self>,
        secret_requests: HashMap<SecretId, Vec<SecretRequest>>,
        requester_info: SecretRequesterInfo,
    ) -> Result<(HashMap<SecretId, Vec<SecretRequest>>, SecretsBox), AppError> {
        let secret_ids: Vec<SecretId> = secret_requests.keys().copied().collect();
        let local_ids = self.probe_secrets(secret_ids).await?;

        let local_secrets = {
            let store_guard = self.store.read().await;
            local_ids
                .iter()
                .filter_map(|id| store_guard.get(id).map(|s| (*id, s.clone())))
                .collect::<BTreeMap<_, _>>()
        };

        let missing: HashMap<SecretId, Vec<SecretRequest>> = secret_requests
            .into_iter()
            .filter(|(id, _)| !local_ids.contains(id))
            .collect();

        if missing.is_empty() {
            debug!("All secrets requested are already stored locally");
            let secrets_box = self.create_secrets_box(&local_secrets, &requester_info)?;
            return Ok((HashMap::new(), secrets_box));
        }

        let threshold = 2;
        let request_id = {
            let mut counter = self.request_counter.lock().await;
            *counter += 1;
            *counter
        };

        let (tx, rx) = oneshot::channel();

        {
            let mut pending_guard = self.pending.lock().await;
            pending_guard.insert(
                request_id,
                PendingRequest {
                    requested_ids: missing.clone(),
                    requester_info: requester_info.clone(),
                    threshold,
                    collected: HashMap::new(),
                    responder: tx,
                },
            );
        }

        let missing_requests = missing.clone();
        self.p2p_secrets_sender
            .clone()
            .try_send(SecretsMessage::PublishSecretsRequest {
                request_id,
                secret_requests: missing_requests.into_iter().collect(),
                requester_info,
            })
            .map_err(|e| AppError::Service(format!("Failed to send secrets request: {}", e)))?;

        let service = Arc::clone(self);
        tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
            if let Err(e) = service.timeout_pending_request(request_id).await {
                error!("Error timing out pending request {}: {}", request_id, e);
            }
        });

        let (remaining_requests, secrets_box) = rx
            .await
            .map_err(|e| AppError::Service(format!("Response channel closed: {}", e)))??;

        match self.extract_secrets_from_box(&secrets_box) {
            Ok(secrets) => {
                if let Err(e) = self.store_secrets(secrets).await {
                    warn!("Failed to store received secrets: {}", e);
                }
            }
            Err(e) => {
                warn!("Failed to extract secrets from box: {}", e);
            }
        }

        Ok((remaining_requests, secrets_box))
    }

    fn create_secrets_box(
        &self,
        secrets: &BTreeMap<SecretId, Secret>,
        requester_info: &SecretRequesterInfo,
    ) -> Result<SecretsBox, AppError> {
        let serialized_secrets = serde_json::to_vec(secrets)
            .map_err(|e| AppError::Service(format!("Failed to serialize secrets: {}", e)))?;

        Ok(SecretsBox {
            alg: "AES-256-GCM+Ed25519".to_string(),
            nonce: vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            sender_public_key: vec![1, 2, 3, 4, 5], // Mock public key
            payload: serialized_secrets,
            signature: vec![10, 20, 30, 40, 50], // Mock signature
        })
    }

    fn extract_secrets_from_box(&self, secrets_box: &SecretsBox) -> Result<Vec<Secret>, AppError> {
        let secrets: BTreeMap<SecretId, Secret> = serde_json::from_slice(&secrets_box.payload)
            .map_err(|e| AppError::Service(format!("Failed to deserialize secrets: {}", e)))?;

        Ok(secrets.into_values().collect())
    }

    pub async fn store_secrets(&self, secrets: Vec<Secret>) -> Result<(), AppError> {
        let mut guard = self.store.write().await;
        for secret in secrets {
            guard.insert(secret.id, secret);
        }
        Ok(())
    }

    pub async fn handle_incoming_secret_batch_request(
        self: &Arc<Self>,
        request_id: u64,
        items: Vec<SecretId>,
        requester_info: SecretRequesterInfo,
    ) -> SecretsBox {
        let snapshot = self.store.read().await;
        let found: BTreeMap<SecretId, Secret> = items
            .iter()
            .filter_map(|id| snapshot.get(id).map(|sec| (*id, sec.clone())))
            .collect();

        match self.create_secrets_box(&found, &requester_info) {
            Ok(box_) => box_,
            Err(e) => {
                error!("Failed to create secrets box: {}", e);
                SecretsBox {
                    alg: "AES-256-GCM+Ed25519".to_string(),
                    nonce: vec![],
                    sender_public_key: vec![],
                    payload: vec![],
                    signature: vec![],
                }
            }
        }
    }

    pub async fn handle_incoming_secret_batch_response(
        &self,
        request_id: u64,
        secrets_box: SecretsBox,
    ) -> Result<(), AppError> {
        let mut pending_guard = self.pending.lock().await;

        let req = match pending_guard.get_mut(&request_id) {
            Some(req) => req,
            None => return Ok(()),
        };

        let secrets = match self.extract_secrets_from_box(&secrets_box) {
            Ok(secrets) => secrets,
            Err(e) => {
                warn!("Failed to extract secrets from box: {}", e);
                return Err(e);
            }
        };

        for secret in secrets {
            req.collected.insert(secret.id, secret);
        }

        if req.collected.len() >= req.threshold {
            if let Some(done) = pending_guard.remove(&request_id) {
                let collected_secrets: BTreeMap<SecretId, Secret> =
                    done.collected.into_iter().collect();

                match self.create_secrets_box(&collected_secrets, &done.requester_info) {
                    Ok(final_box) => {
                        let mut remaining = done.requested_ids;
                        for id in collected_secrets.keys() {
                            remaining.remove(id);
                        }

                        let _ = done.responder.send(Ok((remaining, final_box)));
                    }
                    Err(e) => {
                        let _ = done.responder.send(Err(AppError::Service(format!(
                            "Failed to create secrets box: {}",
                            e
                        ))));
                    }
                }
            }
        }

        Ok(())
    }

    async fn timeout_pending_request(&self, request_id: u64) -> Result<(), AppError> {
        let mut pending_guard = self.pending.lock().await;

        let req = match pending_guard.remove(&request_id) {
            Some(req) => req,
            None => return Ok(()),
        };

        if !req.collected.is_empty() {
            let collected_secrets: BTreeMap<SecretId, Secret> = req.collected.into_iter().collect();

            match self.create_secrets_box(&collected_secrets, &req.requester_info) {
                Ok(secrets_box) => {
                    let mut remaining = req.requested_ids;
                    for id in collected_secrets.keys() {
                        remaining.remove(id);
                    }

                    let _ = req.responder.send(Ok((remaining, secrets_box)));
                }
                Err(e) => {
                    let _ = req.responder.send(Err(AppError::Service(format!(
                        "Failed to create secrets box: {}",
                        e
                    ))));
                }
            }
        } else {
            let empty_box = SecretsBox {
                alg: "AES-256-GCM+Ed25519".to_string(),
                nonce: vec![],
                sender_public_key: vec![],
                payload: vec![],
                signature: vec![],
            };

            let _ = req.responder.send(Ok((req.requested_ids, empty_box)));
        }

        Ok(())
    }
}
