[package]
name = "nxcc-vm-base"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
hyper-util = { version = "0.1.19", features = ["tokio"] }
nxcc-attestation = { path = "../../attestation", optional = true }
nxcc-interface = { path = "../../interface" }
parking_lot = "0.12.5"
rcgen = { version = "0.14.7", features = ["x509-parser"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "net", "sync"] }
tokio-stream = { version = "0.1.18" }
tokio-vsock = { version = "0.7.2", optional = true, features = ["tonic014"] }
tonic = { version = "0.14.2", features = ["tls-aws-lc", "transport"] }
tower = { version = "0.5.3", features = ["util"] }
tracing = "0.1.44"

[features]
default = ["uds"]
uds = []
vsock = ["tokio-vsock"]
tcp = []
test = ["nxcc-attestation"] # enables mock client

[dev-dependencies]
http = "1.4.0"
nxcc-attestation = { path = "../../attestation" }
pem = "3.0.6"
rand = "0.9.3"
rustls = { version = "0.23", features = ["aws-lc-rs"] }
x509-parser = "0.18.0"
