[package]
name = "nxcc-vm-base"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "env"] }
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
hyper-util = { version = "0.1.11", features = ["tokio"] }
nxcc-interface = { path = "../../interface" }
parking_lot = "0.12.3"
rcgen = { version = "0.14.3", features = ["x509-parser"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.15"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros", "net", "sync"] }
tokio-stream = { version = "0.1.17" }
tokio-vsock = { version = "0.7.2", optional = true, features = ["tonic014"] }
tonic = { version = "0.14.1", features = ["tls-aws-lc", "transport"] }
tower = { version = "0.5.2", features = ["util"] }
tracing = "0.1.41"

[features]
default = ["uds"]
uds = []
vsock = ["tokio-vsock"]
tcp = []
test = [] # enables mock client

[dev-dependencies]
http = "1.1.0"
pem = "3.0.5"
rand = "0.8.5"
rustls = { version = "0.23", features = ["aws-lc-rs"] }
x509-parser = "0.17.0"
